import { Poppins } from 'next/font/google'
import WhatsappIcon from "./components/whatsapp_icon.jsx";

import "./globals.css";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "JC Oficina Mecânica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
        <WhatsappIcon/>
      </body>
    </html>
  );
}
